### ISSUE TITLE
New Github Issue Url in Python

### ISSUE THREAD

**Issue by aligoren** [sindresorhus/new-github-issue-url#1]
Hi Sindre. I just created a repository inspired by this repository. I thought you would want to know this.

Everything is the same with your package. So, a JavaScript developer will not be confused. There is no difference in usage instructions.

[https://github.com/aligoren/new-github-issue-url-py](https://github.com/aligoren/new-github-issue-url-py)

Thanks for this repo. I used in my project.

**Comment by sindresorhus** [comment]
👍 Nice work :)
